version: "3"
services:
  app:
    image: bhanuka2500/ems-backend-api:latest
    container_name: ems-backend-api-deployement-container
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
