version: "3"
services:
  app:
    image: bhanuka2500/ems-backend
    container_name: ems-backend-api-deployement-container
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - $APPDATA/Microsoft/UserSecrets:/home/ubuntu/EMS-Backend/

