version: "3"
services:
  emsbackendapi:
    image: ${DOCKER_REGISTRY-}bhanuka2500/ems-backend-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
